### PR TITLE
Edit Style

### PR DESCRIPTION
**Pull request by aerograf**
Edit Style

### CODE REVIEW

**Comment by mambax7** [comment]
"This branch has conflicts that must be resolved"
Can you fix the conflicts and re-submit? 
Thanks!

**Comment by aerograf** [comment]
I can not find where the error is ...
All took away from you, and why gives an error I do not understand ....
excuse me

**Comment by mambax7** [comment]
Before you commit your changes, it's always good to check the Network view:
https://github.com/mambax7/myiframe/network

There you could see that since you forked the module, I've made some changes, so before you commit, you should check if there are conflicts between the files:
image

**Comment by mambax7** [comment]
Normally, when you submit a Pull Request, GitHub tells you that there are conflicts. For example here,  I can see:
Conflicting files
docs/changelog.txt
xoops_version.php

image

**Comment by mambax7** [comment]
To fix that, you can download the current version of the "Upstream" code, (i.e. the module that you forked) , and then use something like WinMerge to compare the differences, and see the conflicts. 
Once you fix the conflicts, you can submit it without any problems...

**Comment by aerograf** [comment]
Ok. I will sort this out :-(

**Comment by mambax7** [comment]
You can see the conflicts here: https://github.com/mambax7/myiframe/pull/1/conflicts
For example, I've changed the file name of the logo to: "logoModule", but you kept the old one, i.e. now you would overwrite my changes:
image

**Comment by mambax7** [comment]
Let me know, if you need help to sort it out. 
The conflicts are very small, and I could resolve it myself, but it's better if I you learn how to check before submission, so in the future there are no conflicts :)

**Comment by aerograf** [comment]
I made a change, but something else is wrong ....

**Comment by mambax7** [comment]
Always look at: https://github.com/mambax7/myiframe/pull/1/conflicts

**Comment by mambax7** [comment]
The changelog is still not fixed.
And in xoops_version.php there are differences in lines:
image

**Comment by mambax7** [comment]
I fixed the lines in xoops_version.php :)

**Comment by mambax7** [comment]
Can you fix the changelog.txt and resubmit?

**Comment by mambax7** [comment]
Good job! Now it's committed

**Comment by aerograf** [comment]
Thank you.
Here's where I did not right ... :-(
https://github.com/XoopsModules25x/tag
https://github.com/XoopsModules25x/lexikon

**Comment by mambax7** [comment]
At the moment, we don't add foreign languages directly to the module. We keep only English, and foreign languages normally go to Transifex: https://www.transifex.com/xoops/ or to:
https://github.com/xoopslanguages
In your case, if you maintain the module, you can keep Russian too.

**Comment by aerograf** [comment]
I participate in the support:
 https://www.transifex.com/xoops/ 
I will also support:
 https://github.com/xoopslanguages
Modules have made changes that relate not only to cyrillic characters, but the ability to use any complex encodings. Of course, if it is interesting for users of modules.

**Pull request merged**
